apiVersion: v2
name: persistue
description: Automatically deploy Chronos UE Persister - if a UE crashes (including deliberately) whilst persistue is running, it will restart automatically
type: application
version: 0.1.0
appVersion: 0.1.0
