apiVersion: v1
kind: Pod
metadata:
  name: persistue
spec:
  terminationGracePeriodSeconds: 10
  hostNetwork: true
  containers:
  - name: persistue
    image: python:trixie
    imagePullPolicy: {{ .Values.imagePullPolicy | quote }}
    command: ["python3", "-m", "http.server", "--bind", {{ .Values.globalSCIP | quote }}, {{ .Values.ueStartSignalPort | quote }}]
    stdin: true
    tty: true
  nodeSelector:
    kubernetes.io/hostname: globalsc
