apiVersion: v1
kind: Pod
metadata:
  name: irtt
spec:
  terminationGracePeriodSeconds: 10
  hostNetwork: true
  containers:
  - name: irtt
    image: {{ .Values.ueDataPlaneImage | quote }}
    imagePullPolicy: {{ .Values.imagePullPolicy | quote }}
    command: ["irtt", "server", "-b", {{ .Values.globalSCIP | quote }}, "-i", "0"]
    stdin: true
    tty: true
  nodeSelector:
    kubernetes.io/hostname: globalsc
