# Docker images
coreImage: docker.io/andrewferguson/phobos-core:large2
globalSCImage: docker.io/andrewferguson/phobos-proxy-5g:a95bc82e
gNBImage: docker.io/andrewferguson/gnb-dockerbuild:killme
proxyImage: docker.io/andrewferguson/phobos-proxy-5g:a95bc82e
ueImage: docker.io/andrewferguson/phobos-nrue:tddwithnc
ueDataPlaneImage: docker.io/andrewferguson/phobos-dataplane:v1

# Number of nodes
numberGNBNodes: 90
numberProxyNodes: 40

# IPs
globalSCIP: 10.4.1.1

# Number of UE and gNB
numberGNB: 10000
numberUE: 10000

# Data plane for UEs
ueDataPlane: irtt
ueDataPlaneWaitTime: 0.5
ueDataPlanePingSleepTime: 0.5
ueDataPlaneIrttSleepTime: 0.5

# Enables large scale features
gnbRandomStartupDelay: True
ueStartSignalWait: True
ueStartSignalPort: 8000
ueNineLogging: True
imagePullPolicy: IfNotPresent
dilateFirstNode: False
